# GitLab CI/CD Pipeline for ArXiv App (macOS)
# Simple pipeline to build and create releases

stages:
  - build
  - release

variables:
  APP_NAME: "ArXiv App"
  SCHEME: "ArXiv App"
  PROJECT_PATH: "ArXiv App.xcodeproj"
  BUILD_PATH: "build"

build_app:
  stage: build
  tags:
    - macos
  script:
    - echo "Building app..."
    - mkdir -p "$BUILD_PATH"
    - xcodebuild -project "$PROJECT_PATH" -scheme "$SCHEME" -configuration Release -derivedDataPath "$BUILD_PATH"
    - cp -R "$BUILD_PATH/Build/Products/Release/$APP_NAME.app" "./$APP_NAME.app"
  artifacts:
    paths:
      - "$APP_NAME.app"
    expire_in: 1 week
  only:
    - main
    - develop
    - merge_requests

release_app:
  stage: release
  tags:
    - macos
  script:
    - echo "Creating release..."
    - zip -r "$APP_NAME.zip" "$APP_NAME.app"
    - >
      glab release create "v-$CI_COMMIT_SHORT_SHA" "$APP_NAME.zip"
      --notes "Automated release for commit $CI_COMMIT_SHORT_SHA"
  only:
    - main
